- name: Install Maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven-setup

- name: Setup Application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: maven package
  ansible.builtin.command: mvn clean package
  args:
      chdir: /app

- name: rename jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
      chdir: /app
    
- name: Load schema
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mysql-schema

- name: Systemd set up
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup

