- name: Check roboshop user exists or not 
  ansible.builtin.command: id roboshop
  register: out # output is a variable name 
  ignore_errors: true

- when: out.rc != 0
  name: Create roboshop user 
  become: yes # we need sudo acess for this  task only 
  ansible.builtin.user:
    name: roboshop

- name: Create /app directory
  ansible.builtin.stat:
    path: /app
  register: directory

- name: Print the directory stats
  ansible.builtin.debug:
    msg: "Output is {{directory}} "

- when: directory.stat.exists == False
  name: Creating the directory file and folders
  ansible.builtin.file:
    path: /app
    state: directory
  
- name: "download {{component}} artifact"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp
  
- name: archive the file 
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes

  