- name: copy mongo repo to yum.repos.d
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
  
- name: Install Mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load schema 
  ansible.builtin.command: "mongo --host mongodb.learndevcloud.online < /app/schema/{{component}}.js"